// <auto-generated />
namespace Ruben.Books.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class LinkBookBadgeToReadingInsteadOfBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkBookBadgeToReadingInsteadOfBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201408111744260_LinkBookBadgeToReadingInsteadOfBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
