//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruben.Books.CommandLine.OldDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class boeken
    {
        public boeken()
        {
            this.Readings = new HashSet<boekgelezen>();
            this.GenreLinks = new HashSet<boekgenre>();
        }
    
        public int boekID { get; set; }
        public string auteurs { get; set; }
        public string titel { get; set; }
        public string isbn { get; set; }
        public Nullable<int> jaar { get; set; }
        public Nullable<int> blz { get; set; }
        public bool owned { get; set; }
        public string tags { get; set; }
    
        public virtual ICollection<boekgelezen> Readings { get; set; }
        public virtual ICollection<boekgenre> GenreLinks { get; set; }
    }
}
