//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruben.Books.CommandLine.OldDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class genres
    {
        public genres()
        {
            this.BookGenreLinks = new HashSet<boekgenre>();
        }
    
        public int genreID { get; set; }
        public string naam { get; set; }
        public string omschrijving { get; set; }
        public sbyte group { get; set; }
    
        public virtual ICollection<boekgenre> BookGenreLinks { get; set; }
    }
}
